### ISSUE TITLE
Traceback on info [router] and when clicking on a node when in sim-mode

### ISSUE THREAD

**Issue by runborg** [UNINETT/PyMetric#3]
When in sim mode the application presents a traceback when pressing a node in the plot-tree:

```
(sim) (1c/107:5:0n) >>> Information for node kjeller-gw1:
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backends/backend_tkagg.py", line 395, in button_press_event
    FigureCanvasBase.button_press_event(self, x, y, num, dblclick=dblclick, guiEvent=event)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backend_bases.py", line 1785, in button_press_event
    self.callbacks.process(s, mouseevent)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/cbook.py", line 527, in process
    proxy(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/cbook.py", line 405, in __call__
    return mtd(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backend_bases.py", line 1671, in pick
    self.figure.pick(mouseevent)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/artist.py", line 354, in pick
    a.pick(mouseevent)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 3154, in pick
    martist.Artist.pick(self, args[0])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/artist.py", line 354, in pick
    a.pick(mouseevent)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/artist.py", line 343, in pick
    self.figure.canvas.pick_event(mouseevent, self, **prop)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backend_bases.py", line 1751, in pick_event
    self.callbacks.process(s, event)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/cbook.py", line 527, in process
    proxy(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/cbook.py", line 405, in __call__
    return mtd(*args, **kwargs)
  File "/Users/runarb/src/metric/pymetric/plotting.py", line 123, in picktest
    self.command.fromui(nodes[i])
  File "/Users/runarb/src/metric/pymetric/command.py", line 71, in fromui
    self.do_info(node)
  File "/Users/runarb/src/metric/pymetric/command.py", line 543, in do_info
    infohash = model.get_node_info(args)
  File "/Users/runarb/src/metric/pymetric/model.py", line 744, in get_node_info
    G.edges(node, data=True))
  File "/Users/runarb/src/metric/pymetric/model.py", line 743, in <lambda>
    + " (" + str(int(x[2])) + ")",
TypeError: int() argument must be a string or a number, not 'dict'
```

**Comment by runborg** [comment]
as a note, this works when not in sim-mode

**Comment by runborg** [comment]
This also happens when using the info [router] command
