### ISSUE TITLE
One-way-link between two nodes in pajek rases keyError on load

### ISSUE THREAD

**Issue by runborg** [UNINETT/PyMetric#7]
When loading a pajek with a one-way link networkx failes computation with a keyError
```
Traceback (most recent call last):
  File "metrics.py", line 45, in <module>
    cli.cmdloop()
  File "/Users/runarb/src/metric/pymetric/command.py", line 64, in cmdloop
    Cmd.cmdloop(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/Users/runarb/src/metric/pymetric/command.py", line 424, in do_plot
    self.gui.plot(G, graphdata, edge_cmap=cmap, edge_capa=capa)
  File "/Users/runarb/src/metric/pymetric/plotting.py", line 292, in plot
    pos=data['pos'])
  File "/Users/runarb/src/metric/pymetric/plotting.py", line 350, in _plot_edge_labels
    if d < 70 and G[v][u]['weight'] == w['weight']:
  File "/Library/Python/2.7/site-packages/networkx/classes/coreviews.py", line 54, in __getitem__
    return self._atlas[key]
KeyError: 'ifi2-gw4'
```

**Comment by runborg** [comment]
As all links are bi-directional in pymetric, could this inconsistency be checked for when importing the links into pymetric and give a reasonable error message on a fault?
